-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 10:36:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sw2projdb` DEFAULT CHARACTER SET utf8 ;
USE `sw2projdb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw2projdb`.`Preference` (
  `idPreference` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `raEmail` VARCHAR(45) NOT NULL,
  `rdEmail` VARCHAR(45) NOT NULL,
  `resHall` VARCHAR(45) NOT NULL,
  `floorNumber` VARCHAR(4) NULL,
  `roomNumber` VARCHAR(4) NULL,
  PRIMARY KEY (`idPreference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Work Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw2projdb`.`Work Order` (
  `idWork Order` INT NOT NULL,
  `Building` VARCHAR(45) NULL,
  `Coordinates` VARCHAR(45) NULL,
  `Description` TEXT NULL,
  `name` VARCHAR(45) NULL,
  `preferencesID` VARCHAR(45) NULL,
  `raEmail` VARCHAR(45) NULL,
  `rdEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`idWork Order`),
  INDEX `name_idx` (`name` ASC),
  INDEX `raEmail_idx` (`raEmail` ASC),
  INDEX `rdEmail_idx` (`rdEmail` ASC),
  CONSTRAINT `name`
    FOREIGN KEY (`name`)
    REFERENCES `sw2projdb`.`Preference` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `raEmail`
    FOREIGN KEY (`raEmail`)
    REFERENCES `sw2projdb`.`Preference` (`raEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rdEmail`
    FOREIGN KEY (`rdEmail`)
    REFERENCES `sw2projdb`.`Preference` (`rdEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `preferencesID`
    FOREIGN KEY (`idWork Order`)
    REFERENCES `sw2projdb`.`Preference` (`idPreference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw2projdb`.`Status` (
  `idStatus` INT NOT NULL,
  `workOrderID` INT NULL,
  `submissionDate` TIMESTAMP NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idStatus`),
  INDEX `workOrderID_idx` (`workOrderID` ASC),
  CONSTRAINT `workOrderID`
    FOREIGN KEY (`workOrderID`)
    REFERENCES `mydb`.`Work Order` (`idWork Order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
